#!/bin/bash

function failed() {
	echo "$@"
	exit 1
}

cd `dirname $0`
BASE_DIR=$PWD
export DYNCALL_HOME=$BASE_DIR/dyncall

if [[ ! -d "$DYNCALL_HOME" ]]
then
	$BASE_DIR/admin/checkout_and_patch_dyncall.sh src/main/cpp/bridj/dyncall.diff || failed "Failed to checkout and patch dyncall"
fi

MAKE_CMD=make
if [[ "`which gmake`" != "" ]]; then
	MAKE_CMD=gmake
fi

OS=`uname -s | sed s/_NT-.*/_NT/`
ARCH=`uname -m`

case $ARCH in
i86pc|i386|i486|i586|i686|x86)
	ARCH=x86
	;;
x86_64|amd64)
	ARCH=x64
	;;
esac

OS_ARCH=""
case $OS in
WindowsNT)
	case $ARCH in
	x86)
		OS_ARCH=win32
		;;
	x64)
		OS_ARCH=win64
		;;
	esac
	OS="windows"
	;;
Darwin)
	OS="darwin"
	OS_ARCH="darwin_universal"
	;;
Linux)
	case $ARCH in
	arm32)
		if [[ -d /lib/arm-linux-gnueabihf ]] ; then
      OS_ARCH="linux_armhf"
    elif [[ -d /lib/arm-linux-gnueabi ]] ; then
    	OS_ARCH="linux_armel"
  	else
  		failed "Unknown Linux arm flavour: please edit $0 and Platform.java"
		fi
		;;
	esac
	OS="linux"
	;;
SunOS)
	OS="sunos"
	;;
OpenBSD)
	OS="openbsd"
	;;
FreeBSD|GNU/kFreeBSD)
	OS="freebsd"
	;;
NetBSD)
	OS="netbsd"
	;;
esac
OS_ARCH=${OS_ARCH:-${OS}_${ARCH}}

CMDS=$@
if [[ -z "$BRIDJ_TARGETS" ]]; then
	BRIDJ_TARGETS="default"
	if [[ -n "$ANDROID_NDK_HOME" ]] ; then
		BRIDJ_TARGETS="$BRIDJ_TARGETS android" ;
	fi
fi

if [[ "$1" != "clean" && "$FAST" != "1" ]]; then
    mvn generate-sources
fi

if [[ "$DEBUG" == "1" ]]; then
	CONFIG=debug
else
	CONFIG=release
fi

for BRIDJ_TARGET in $BRIDJ_TARGETS ; do
	case $BRIDJ_TARGET in
	default)
		cd $DYNCALL_HOME/dyncall
		sh ./configure
		$MAKE_CMD $@ || failed "Failed building dyncall"

		export DYNCALL_HOME
		export OS
		export ARCH
		export CONFIG
		export OUT_DIR=$BASE_DIR/src/main/resources/org/bridj/lib/$OS_ARCH
		export OBJ_DIR=target/build/${OS}_${ARCH}_${CONFIG}

		cd $BASE_DIR/src/main/cpp/bridj
		$MAKE_CMD $@ || failed "Build of lib failed"

		export OUT_DIR=$BASE_DIR/src/test/resources/org/bridj/lib/$OS_ARCH

		cd $BASE_DIR/src/test/cpp/test
		$MAKE_CMD $@ || failed "Build of test lib failed"

		cd $BASE_DIR/src/test/cpp/dependsOnTest
		$MAKE_CMD $@ || failed "Build of dependsOnTest lib failed"
		;;
	android)
		$BASE_DIR/src/main/cpp/bridj/MakeAndroid.sh $@
		;;
	esac
done
