#!/bin/bash

function failIfHas {
    grep "$1" > /dev/null && ( echo "$2" ; exit 1 )
}
function fail {
    echo "$@"
    exit 1
}

for F in target/bridj*.jar ; do
    if [[ ! $F =~ .*(javadoc|sources).* ]]; then
        echo ""
        echo $F
        CONTENTS=`unzip -l $F`
        echo "$CONTENTS" | grep BridJ.class > /dev/null || fail "Does not have BridJ"
        if [[ $F =~ .*android.* || $F =~ .*SNAPSHOT.jar ]]; then
            echo "$CONTENTS" | grep DexFormat.class > /dev/null || fail "Does not have Dex"
        else
            echo "$CONTENTS" | grep DexFormat.class > /dev/null && fail "Has Dex"
        fi 
        echo "$CONTENTS" | egrep "\.so|\.dll|\.dylib" || exit 1
        echo "$CONTENTS" | grep junit && fail "Has JUnit"
    fi
done

echo "
SUCCESS
"
