#!/bin/bash

function failIfHas {
    grep "$1" > /dev/null && ( echo "$2" ; exit 1 )
}
function fail {
    echo "$@"
    exit 1
}

for F in target/bridj*.jar ; do
    if [[ ! $F =~ .*(javadoc|sources).* ]]; then
        echo ""
        echo $F
        CONTENTS=`unzip -l $F`
        echo "$CONTENTS" | grep BridJ.class > /dev/null || fail "Does not have BridJ"
        ANDROID_CLASSES="DexFormat AndroidClassDefiner AndroidSupport"
        if [[ $F =~ .*android.* ]]; then
            for CLS in $ANDROID_CLASSES; do
                echo "$CONTENTS" | grep $CLS.class > /dev/null || fail "Does not have class $CLS"
                echo "   Has class $CLS"
            done
        else
            for CLS in $ANDROID_CLASSES; do
                echo "$CONTENTS" | grep $CLS.class > /dev/null && fail "Has class $CLS"
            done
            echo "$CONTENTS" | grep -i Android && fail "Has some android references"
        fi 
        echo "$CONTENTS" | egrep "\.so|\.dll|\.dylib" || exit 1
        echo "$CONTENTS" | grep junit && fail "Has JUnit"
    fi
done

echo "
SUCCESS
"
