package org.bridj.jawt;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : jawt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("jawt") 
public class JAWT_Rectangle extends StructObject {
	@Field(0) 
	public int x() {
		return this.io.getIntField(this, 0);
	}
	@Field(1) 
	public int y() {
		return this.io.getIntField(this, 1);
	}
	@Field(2) 
	public int width() {
		return this.io.getIntField(this, 2);
	}
	@Field(3) 
	public int height() {
		return this.io.getIntField(this, 3);
	}
}
