package org.bridj.jawt;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.jawt.JawtLibrary.JNIEnv;
import org.bridj.ann.Convention;
/**
 * <i>native declaration : jawt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("jawt") 
@Convention(Convention.Style.StdCall)
public class JAWT extends StructObject {
	/**
	 * Version of this structure.  This must always be set before<br>
	 * calling JAWT_GetAWT()
	 */
	@Field(0) 
	public int version() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * Version of this structure.  This must always be set before<br>
	 * calling JAWT_GetAWT()
	 */
	@Field(0) 
	public JAWT version(int version) {
		this.io.setIntField(this, 0, version);
		return this;
	}
    
    @Field(1)
    public Pointer<GetDrawingSurface_callback> GetDrawingSurface() {
		return this.io.getPointerField(this, 1);
	}
    @Field(2)
    public Pointer<FreeDrawingSurface_callback> FreeDrawingSurface() {
		return this.io.getPointerField(this, 2);
	}
    @Field(3)
    public Pointer<Lock_callback> Lock() {
		return this.io.getPointerField(this, 3);
	}
    @Field(4)
    public Pointer<Unlock_callback> Unlock() {
		return this.io.getPointerField(this, 4);
	}
    @Field(5)
    public Pointer<GetComponent_callback> GetComponent() {
		return this.io.getPointerField(this, 5);
	}
    
	public static abstract class GetDrawingSurface_callback extends Callback {
		public abstract Pointer<org.bridj.jawt.JAWT_DrawingSurface > invoke(Pointer<JNIEnv > env, Pointer<? > target);
	};
	/// <i>native declaration : jawt.h:236</i>
	public static abstract class FreeDrawingSurface_callback extends Callback {
		public abstract void invoke(Pointer<org.bridj.jawt.JAWT_DrawingSurface > ds);
	};
	/// <i>native declaration : jawt.h:242</i>
	public static abstract class Lock_callback extends Callback {
		public abstract void invoke(Pointer<JNIEnv > env);
	};
	/// <i>native declaration : jawt.h:247</i>
	public static abstract class Unlock_callback extends Callback {
		public abstract void invoke(Pointer<JNIEnv > env);
	};
	/// <i>native declaration : jawt.h:259</i>
	public static abstract class GetComponent_callback extends Callback {
		public abstract Pointer<? > invoke(Pointer<JNIEnv > env, Pointer<? > platformInfo);
	};
}
