/*
 * BridJ - Dynamic and blazing-fast native interop for Java.
 * http://bridj.googlecode.com/
 *
 * Copyright (c) 2010-2013, Olivier Chafik (http://ochafik.com/)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Olivier Chafik nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY OLIVIER CHAFIK AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.bridj.cpp.com;

import org.bridj.CRuntime;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;

/**
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a
 * href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few
 * opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a
 * href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Runtime(CRuntime.class)
public class DECIMAL extends StructObject {
    /// C type : USHORT

    @Field(0)
    public short wReserved() {
        return this.io.getShortField(this, 0);
    }
    /// C type : USHORT

    @Field(0)
    public DECIMAL wReserved(short wReserved) {
        this.io.setShortField(this, 0, wReserved);
        return this;
    }
    /// C type : USHORT

    public final short wReserved_$eq(short wReserved) {
        wReserved(wReserved);
        return wReserved;
    }

    @Field(1)
    public byte scale() {
        return this.io.getByteField(this, 1);
    }

    @Field(1)
    public DECIMAL scale(byte scale) {
        this.io.setByteField(this, 1, scale);
        return this;
    }

    public final byte scale_$eq(byte scale) {
        scale(scale);
        return scale;
    }

    @Field(2)
    public byte sign() {
        return this.io.getByteField(this, 2);
    }

    @Field(2)
    public DECIMAL sign(byte sign) {
        this.io.setByteField(this, 2, sign);
        return this;
    }

    public final byte sign_$eq(byte sign) {
        sign(sign);
        return sign;
    }
    /// C type : ULONG

    @Field(3)
    public int Hi32() {
        return this.io.getIntField(this, 3);
    }
    /// C type : ULONG

    @Field(3)
    public DECIMAL Hi32(int Hi32) {
        this.io.setIntField(this, 3, Hi32);
        return this;
    }
    /// C type : ULONG

    public final int Hi32_$eq(int Hi32) {
        Hi32(Hi32);
        return Hi32;
    }

    @Field(4)
    public long Lo64() {
        return this.io.getLongField(this, 4);
    }

    @Field(4)
    public DECIMAL Lo64(long Lo64) {
        this.io.setLongField(this, 4, Lo64);
        return this;
    }

    public final long Lo64_$eq(long Lo64) {
        Lo64(Lo64);
        return Lo64;
    }
}
