/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Pointer_OrderedPointer */

#ifndef _Included_org_bridj_Pointer_OrderedPointer
#define _Included_org_bridj_Pointer_OrderedPointer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
