/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Pointer_DisorderedPointer */

#ifndef _Included_org_bridj_Pointer_DisorderedPointer
#define _Included_org_bridj_Pointer_DisorderedPointer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bridj_Pointer_DisorderedPointer_UNKNOWN_VALIDITY
#define org_bridj_Pointer_DisorderedPointer_UNKNOWN_VALIDITY -1LL
#undef org_bridj_Pointer_DisorderedPointer_NO_PARENT
#define org_bridj_Pointer_DisorderedPointer_NO_PARENT 0LL
#undef org_bridj_Pointer_DisorderedPointer_LRU_POINTER_CACHE_SIZE
#define org_bridj_Pointer_DisorderedPointer_LRU_POINTER_CACHE_SIZE 8L
#undef org_bridj_Pointer_DisorderedPointer_LRU_POINTER_CACHE_TOLERANCE
#define org_bridj_Pointer_DisorderedPointer_LRU_POINTER_CACHE_TOLERANCE 1L
#ifdef __cplusplus
}
#endif
#endif
