/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Pointer */

#ifndef _Included_org_bridj_Pointer
#define _Included_org_bridj_Pointer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bridj_Pointer_UNKNOWN_VALIDITY
#define org_bridj_Pointer_UNKNOWN_VALIDITY -1LL
#undef org_bridj_Pointer_NO_PARENT
#define org_bridj_Pointer_NO_PARENT 0LL
#undef org_bridj_Pointer_LRU_POINTER_CACHE_SIZE
#define org_bridj_Pointer_LRU_POINTER_CACHE_SIZE 8L
#undef org_bridj_Pointer_LRU_POINTER_CACHE_TOLERANCE
#define org_bridj_Pointer_LRU_POINTER_CACHE_TOLERANCE 1L
#ifdef __cplusplus
}
#endif
#endif
