/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Platform */

#ifndef _Included_org_bridj_Platform
#define _Included_org_bridj_Platform
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bridj_Platform_DELETE_OLD_BINARIES_AFTER_MILLIS
#define org_bridj_Platform_DELETE_OLD_BINARIES_AFTER_MILLIS 86400000LL
/*
 * Class:     org_bridj_Platform
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bridj_Platform_init
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    sizeOf_size_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_sizeOf_1size_1t
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    sizeOf_time_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_sizeOf_1time_1t
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    sizeOf_wchar_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_sizeOf_1wchar_1t
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    sizeOf_ptrdiff_t
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_sizeOf_1ptrdiff_1t
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    sizeOf_long
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_sizeOf_1long
  (JNIEnv *, jclass);

/*
 * Class:     org_bridj_Platform
 * Method:    getMaxDirectMappingArgCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bridj_Platform_getMaxDirectMappingArgCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
