/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_Platform_DeleteFiles */

#ifndef _Included_org_bridj_Platform_DeleteFiles
#define _Included_org_bridj_Platform_DeleteFiles
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bridj_Platform_DeleteFiles_TRY_DELETE_EVERY_MILLIS
#define org_bridj_Platform_DeleteFiles_TRY_DELETE_EVERY_MILLIS 50LL
#undef org_bridj_Platform_DeleteFiles_FAIL_AFTER_MILLIS
#define org_bridj_Platform_DeleteFiles_FAIL_AFTER_MILLIS 10000LL
#ifdef __cplusplus
}
#endif
#endif
