/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_BridJ_Switch */

#ifndef _Included_org_bridj_BridJ_Switch
#define _Included_org_bridj_BridJ_Switch
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
