/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bridj_BridJ */

#ifndef _Included_org_bridj_BridJ
#define _Included_org_bridj_BridJ
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
